### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by chakrapani123** [mongoeye/mongoeye#13]
hello,

first of all , great job on this tool ..i loved it..i have been trying to work on it and its been super great so far. i ran into this issue especially with user accounts. say i have mongodb host A which has typically admin, local, hostdb and so on..and i have user part of hostdb and i have created this user in admin db too and when i try to connect to admin db and get keys in collections it errors out ..which makes sense. but if i have user a created in admin db with readanydatabase role and try to execute this 

mongoeye --host host1:port1 --db hostdb --col hostcol-u username -p password -s first:100 -d 10 -f table

i get check ur creds they are not accurate . i was able to connect fine with these creds on my robo3t..however when i added auth-mechanism

mongoeye --host host1:port1 --db admin --col system.keys -u username -p password -s first:100 -d 10 -f table --auth-mech SCRAM-SHA-1
it still fails. wondering if there is a way to get past this authentication issue

thanks
chakri

**Comment by michaljurecko** [comment]
Hi,

At the moment, I am not actively developing this project, but I will try to find time to check this issue and also fix failing builds.

**Comment by chakrapani123** [comment]
thanks
