### ISSUE TITLE
Releases `amd64` folder

### ISSUE THREAD

**Issue by dolbyzerr** [mongoeye/mongoeye#8]
I've created simple node wrapper: [mongoeye-node](https://github.com/dolbyzerr/mongoeye-node)

I have a question regarding releases folder structure, so currently, zip release contains:

`mongoeye/{platform}/{architecture}/mongoeye`

and for some reason, `architecture` is either `amd64` or `arm` (for linux).

Is there any chance that architecture will be https://nodejs.org/api/os.html complaint, e.g. `x64`?

And thanks for the amazing project!

**Comment by michaljurecko** [comment]
Hi, I'm looking forward to your interest in this project.

In different programming languages, architectures are unfortunately named differently.

**I follow Golang way**. See:
https://golang.org/doc/install/source#introduction

Perhaps it will not be a big problem for you,
but for that reason I do not plan to change directory structure of release.

Thanks for your suggestion and `mongoeye-node`.
