### ISSUE TITLE
Add query example to the docs

### ISSUE THREAD

**Issue by sergeda** [mongoeye/mongoeye#9]
I'm looking for a way to exclude some fields from the scanning.
Is there any way to do this using query? Or you should add projection support for this to work?

**Comment by michaljurecko** [comment]
I'm looking forward to your interest in this project!

Query (`--query`) parameter is using [$match](https://docs.mongodb.com/manual/reference/operator/aggregation/match/) aggregation.

Your usecase need [$project](https://docs.mongodb.com/manual/reference/operator/aggregation/project/) aggregation.

I will try to implement it (`--project` parameter), it should not be a problem.

**Comment by sergeda** [comment]
@webrouse Thanks. This would be great

**Comment by michaljurecko** [comment]
Try (documentation updated too): https://github.com/mongoeye/mongoeye/releases/tag/v0.4

**Please let me know if it works as expected.**

Thank you ;)

**Comment by sergeda** [comment]
Thank you, @webrouse 
But can you add example queries to the doc? I've tried `--project {"Field": 0}` and `--project '{"Field": 0}'` always got 

> Invalid JSON in 'project' option

**Comment by michaljurecko** [comment]
example: https://asciinema.org/a/148993?t=2:05

 \+

![image](https://user-images.githubusercontent.com/19371734/33166953-46614824-d03c-11e7-9cfc-9d5e66228a67.png)

**Comment by sergeda** [comment]
@webrouse Strange, doing exactly the same thing gives me that error. Is it coming from Mongo or from Mongoeye?

**Comment by michaljurecko** [comment]
From mongoeye, ... OS? shell? 

(I am using Linux/ZSH.)

**Comment by sergeda** [comment]
@webrouse I'm on Windows 7, using default shell

**Comment by michaljurecko** [comment]
Try: https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter

**Comment by sergeda** [comment]
@webrouse Tried all the combinations without luck :(

**Comment by michaljurecko** [comment]
I'll try it on windows, ...

**Comment by michaljurecko** [comment]
This should be working: `--project "{\"Field\": 0}"`

![image](https://user-images.githubusercontent.com/19371734/33230094-342053ba-d1dd-11e7-84ee-5d743be52010.png)


@sergeda  Can you please try it?

**Comment by sergeda** [comment]
Thanks @webrouse This works, but gives me error 

> The top-level _id field is the only field currently supported for exclusion

Seems like Mongo restriction :(

**Comment by michaljurecko** [comment]
Yes, but you can positively list fields for analysis, ... or update MongoDB to a newer version.
